import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['src/**/*.test.ts'],
    exclude: ['src/**/*.int.test.ts', 'node_modules/**'],
    environment: 'node',
    coverage: {
      provider: 'v8',
      reporter: ['text-summary', 'lcov', 'json-summary'],
      reportsDirectory: 'coverage',
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.corpus.ts',
        // The entrypoint is wiring: CI's container-stack job boots it for real,
        // and mocking Nest's bootstrap to reach it would test the mock.
        'src/api/main.ts',
        'src/**/*.module.ts',
        // argv in, a file out. What it writes is covered by document.test.ts,
        // and that the committed file matches by `openapi:check` in CI.
        'src/api/openapi/cli.ts',
        // Database behaviour: the session time zone on every connection and
        // real driver errors. Covered by pool.int.test.ts and
        // database-unavailable.int.test.ts against a real MySQL 8.4, which CI
        // runs as its own job. A unit test would assert against a mocked pool.
        'src/core/db/pool.ts',
        'src/core/db/db.service.ts',
        // The migration runner, its registry and the schema dump are MySQL
        // behaviour -- implicit DDL commits, GET_LOCK, SHOW CREATE TABLE --
        // covered by runner.int.test.ts and baseline.int.test.ts against a
        // real MySQL 8.4, and by the CI migrations job end to end.
        'src/core/db/migrator/runner.ts',
        'src/core/db/migrator/registry.ts',
        'src/core/db/migrator/schema-dump.ts',
        // argv in, the runner out; exercised by the CI migrations job.
        'src/core/db/migrator/cli.ts',
        'src/core/db/migrator/dump-cli.ts',
        // The query layer's database behaviour -- Kysely on the real pool,
        // FOR SHARE reads, deadlock retries, the seed -- is proved against
        // MySQL 8.4 by database/terms/transaction/seed .int.test.ts.
        'src/core/db/database.ts',
        'src/core/db/terms.ts',
        'src/core/db/transaction.ts',
        'src/core/db/user-lock.ts',
        'src/core/db/seed/seed.ts',
        'src/core/db/seed/cli.ts',
        'src/core/db/resanitize-cli.ts',
        // Rows in, rows out against MySQL: proved by resanitize.int.test.ts.
        'src/core/db/resanitize.ts',
        // First-login provisioning: ON DUPLICATE KEY, FOR SHARE re-reads and the
        // deadlock retry are MySQL behaviour, proved with barriers against MySQL
        // 8.4 by user.repository.int.test.ts and me/e2e/me.int.test.ts.
        'src/api/users/repositories/user.repository.ts',
        'src/api/users/services/users.service.ts',
        // Profile reads and writes: the visibility predicate in SQL, matched-row
        // counts, the project merge, 404 after a concurrent delete. All MySQL
        // behaviour, proved against MySQL 8.4 (barriers included) by
        // profiles/e2e/profiles.int.test.ts and the repositories' int tests.
        'src/api/profiles/repositories/*.ts',
        'src/api/profiles/services/*.ts',
        'src/api/profiles/utils/*.ts',
        'src/api/profiles/*.controller.ts',
        'src/api/me/services/*.ts',
        // Project reads: the visibility predicate and the filters in SQL, keyset
        // paging on row values, child reads. MySQL behaviour, proved against
        // MySQL 8.4 by projects/e2e/project-reads.int.test.ts.
        'src/api/projects/repositories/*.ts',
        'src/api/projects/services/*.ts',
        'src/api/projects/utils/visibility.ts',
        'src/api/projects/*.controller.ts',
        // Types only; generated by `npm run db:types`.
        'src/core/db/types.generated.ts',
        'src/core/db/column-types.ts',
        // Test-only helpers, never shipped.
        'src/testing/**',
      ],
      // A ratchet, not an aspiration: at or just below what the suite
      // achieves, so coverage cannot silently fall. Raise it as milestones land.
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
  },
});
