/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { Bool, DateText, JsonColumn, LinkList, StringList, TranslationParams } from "./column-types.js";
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Activities {
  details: string | null;
  id: string;
  timestamp: Generated<Date>;
  translationKey: string;
  translationParams: JsonColumn<TranslationParams>;
  type: "profile" | "project";
  userId: string;
}

export interface Certifications {
  credentialUrl: string | null;
  date: string;
  id: string;
  issuer: string;
  name: string;
  sortOrder: Generated<number>;
  userId: string;
}

export interface Education {
  degree: string;
  description: string | null;
  endYear: number | null;
  field: string;
  highlights: JsonColumn<StringList>;
  id: string;
  institution: string;
  sortOrder: Generated<number>;
  startYear: number;
  userId: string;
}

export interface Experience {
  achievements: JsonColumn<StringList>;
  end: string | null;
  id: string;
  organization: string;
  skills: JsonColumn<StringList>;
  sortOrder: Generated<number>;
  start: string;
  summary: string;
  title: string;
  userId: string;
}

export interface Integrations {
  accessToken: string | null;
  createdAt: Generated<Date>;
  externalUserId: string | null;
  id: string;
  integrationType: "github" | "linkedin";
  lastSyncedAt: Date | null;
  refreshToken: string | null;
  status: Generated<"connected" | "not_connected">;
  tokenExpiresAt: Date | null;
  updatedAt: Generated<Date>;
  userId: string;
}

export interface Notifications {
  createdAt: Generated<Date>;
  id: string;
  isRead: Bool;
  link: string | null;
  message: string | null;
  referenceId: string | null;
  referenceType: string | null;
  title: string;
  type: "comment" | "contact_request" | "general" | "project_verified" | "team_accepted" | "team_invite" | "team_rejected";
  userId: string;
}

export interface ProjectAttachments {
  id: string;
  projectId: string;
  sortOrder: Generated<number>;
  thumbnailUrl: string | null;
  title: string | null;
  type: "image" | "link" | "pdf" | "video";
  url: string;
}

export interface Projects {
  aiSummary: string | null;
  category: Generated<"academic" | "course" | "hackathon" | "other" | "personal" | "research">;
  createdAt: Generated<Date>;
  descriptionHtml: string | null;
  files: JsonColumn<LinkList>;
  githubRepoId: number | null;
  heroImageUrl: string | null;
  href: string | null;
  id: string;
  isDraft: Bool;
  isPublic: Bool;
  links: JsonColumn<LinkList>;
  liveDemoUrl: string | null;
  metaCourse: string | null;
  metaEndDate: DateText;
  metaProfessor: string | null;
  metaStartDate: DateText;
  repoForks: number | null;
  repoLanguage: string | null;
  repoLatestCommit: DateText;
  repoReadmeUrl: string | null;
  repoStars: number | null;
  repoUrl: string | null;
  source: Generated<"github" | "manual">;
  status: Generated<"archived" | "completed" | "ongoing">;
  summary: string | null;
  title: string;
  updatedAt: Generated<Date>;
  userId: string;
}

export interface ProjectTags {
  name: string;
  projectId: string;
  sortOrder: Generated<number>;
}

export interface ProjectTeamMembers {
  avatarUrl: string | null;
  createdAt: Generated<Date>;
  id: string;
  name: string;
  projectId: string;
  role: string | null;
  sortOrder: Generated<number>;
  status: Generated<"accepted" | "pending" | "rejected">;
  userId: string | null;
}

export interface ProjectTechnologies {
  name: string;
  projectId: string;
  sortOrder: Generated<number>;
}

export interface Terms {
  name: string;
}

export interface Users {
  auth0Id: string;
  avatarUrl: string | null;
  bio: string | null;
  birthday: DateText;
  contactEmail: string | null;
  createdAt: Generated<Date>;
  email: string | null;
  github: string | null;
  headline: Generated<string>;
  id: string;
  isPublic: Bool;
  linkedin: string | null;
  location: string | null;
  name: string;
  onboardedAt: Date | null;
  phone: string | null;
  twitter: string | null;
  updatedAt: Generated<Date>;
  verified: Bool;
  website: string | null;
}

export interface UserSkills {
  id: string;
  skillName: string;
  sortOrder: Generated<number>;
  userId: string;
}

export interface DB {
  activities: Activities;
  certifications: Certifications;
  education: Education;
  experience: Experience;
  integrations: Integrations;
  notifications: Notifications;
  projectAttachments: ProjectAttachments;
  projects: Projects;
  projectTags: ProjectTags;
  projectTeamMembers: ProjectTeamMembers;
  projectTechnologies: ProjectTechnologies;
  terms: Terms;
  users: Users;
  userSkills: UserSkills;
}
