/**
 * Known XSS bypass shapes, as [name, class, html]. Every one must come out of
 * `sanitizeDescription` inert. Sources: OWASP XSS filter evasion cheat sheet,
 * DOMPurify's and sanitize-html's published mutation-XSS cases, and the 2026
 * sanitize-html advisories (GHSA-jxwj-j7wr-gfrw, -g8qq-57p8-ggw5, -vccv-cmxp-4j9h,
 * -rpr9-rxv7-x643, -9mrh-v2v3-xpfm).
 */
export const CORPUS: readonly (readonly [string, string, string])[] = [
  ['script tag', 'script', '<p>a</p><script>alert(1)</script>'],
  ['script nested split', 'script', '<scr<script>ipt>alert(1)</scr</script>ipt>'],
  ['script upper/null', 'script', '<SCRIPT SRC=//evil/x.js></SCRIPT>'],
  ['img onerror', 'handler', '<img src=x onerror=alert(1)>'],
  ['svg onload', 'svg', '<svg onload=alert(1)>'],
  ['svg script', 'svg', '<svg><script>alert(1)</script></svg>'],
  [
    'svg use xlink',
    'svg',
    '<svg><use xlink:href="data:image/svg+xml;base64,PHN2Zz48L3N2Zz4="/></svg>',
  ],
  [
    'svg animate',
    'svg',
    '<svg><a><animate attributeName=href values=javascript:alert(1) /><text x=20 y=20>x</text></a></svg>',
  ],
  ['math href', 'mathml', '<math href="javascript:alert(1)">CLICK</math>'],
  [
    'math maction',
    'mathml',
    '<math><maction actiontype="statusline#http://x" xlink:href="javascript:alert(1)">x</maction></math>',
  ],
  ['a javascript:', 'url', '<a href="javascript:alert(1)">x</a>'],
  ['a JaVaScRiPt:', 'url', '<a href="JaVaScRiPt:alert(1)">x</a>'],
  [
    'a entity-encoded dec',
    'url',
    '<a href="&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;alert(1)">x</a>',
  ],
  [
    'a entity no semicolon',
    'url',
    '<a href="&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058alert(1)">x</a>',
  ],
  [
    'a hex entity',
    'url',
    '<a href="&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A;alert(1)">x</a>',
  ],
  ['a tab in scheme', 'url', '<a href="jav\tascript:alert(1)">x</a>'],
  ['a newline in scheme', 'url', '<a href="jav&#x0A;ascript:alert(1)">x</a>'],
  ['a leading ctrl', 'url', '<a href="\u0001javascript:alert(1)">x</a>'],
  ['a leading space', 'url', '<a href=" javascript:alert(1)">x</a>'],
  ['a colon entity', 'url', '<a href="javascript&colon;alert(1)">x</a>'],
  ['a vbscript', 'url', '<a href="vbscript:msgbox(1)">x</a>'],
  [
    'a data html',
    'url',
    '<a href="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==">x</a>',
  ],
  ['a protocol-relative', 'url', '<a href="//evil.example/x">x</a>'],
  ['img src javascript', 'url', '<img src="javascript:alert(1)">'],
  ['img srcset', 'url', '<img srcset="javascript:alert(1) 1x">'],
  ['iframe', 'embed', '<iframe src="https://evil.example"></iframe>'],
  ['iframe srcdoc', 'embed', '<iframe srcdoc="<script>alert(1)</script>"></iframe>'],
  ['object', 'embed', '<object data="javascript:alert(1)"></object>'],
  ['embed', 'embed', '<embed src="data:text/html,<script>alert(1)</script>">'],
  ['base', 'embed', '<base href="https://evil.example/"><a href="x">x</a>'],
  ['meta refresh', 'embed', '<meta http-equiv="refresh" content="0;url=javascript:alert(1)">'],
  ['link stylesheet', 'embed', '<link rel=stylesheet href="https://evil.example/x.css">'],
  ['form action', 'form', '<form action="javascript:alert(1)"><input type=submit></form>'],
  ['button formaction', 'form', '<form><button formaction="javascript:alert(1)">x</button></form>'],
  ['input autofocus', 'handler', '<input autofocus onfocus=alert(1)>'],
  ['details ontoggle', 'handler', '<details open ontoggle=alert(1)>x</details>'],
  ['video source onerror', 'handler', '<video><source onerror=alert(1)></video>'],
  ['body onload', 'handler', '<body onload=alert(1)>'],
  ['p style expression', 'style', '<p style="width:expression(alert(1))">x</p>'],
  ['p style url js', 'style', '<p style="background:url(javascript:alert(1))">x</p>'],
  [
    'p style position fixed',
    'style',
    '<p style="position:fixed;top:0;left:0;width:100%;height:100%">overlay</p>',
  ],
  ['style tag import', 'style', '<style>@import "https://evil.example/x.css";</style>x'],
  ['style tag', 'style', '<style>*{background:url(https://evil.example/t)}</style>x'],
  ['class injection', 'style', '<p class="MuiBackdrop-root">x</p>'],
  ['id clobber', 'style', '<a id="__proto__" name="cookie">x</a><img name="body">'],
  ['mXSS svg style', 'mxss', '<svg></p><style><a id="</style><img src=1 onerror=alert(1)>">'],
  [
    'mXSS math mglyph',
    'mxss',
    '<math><mtext><table><mglyph><style><!--</style><img title="--&gt;&lt;img src=1 onerror=alert(1)&gt;">',
  ],
  ['mXSS noscript', 'mxss', '<noscript><p title="</noscript><img src=x onerror=alert(1)>">'],
  [
    'mXSS form nest',
    'mxss',
    '<form><math><mtext></form><form><mglyph><style></math><img src onerror=alert(1)>',
  ],
  [
    'mXSS textarea',
    'mxss',
    '<textarea><p title="</textarea><img src=x onerror=alert(1)>"></textarea>',
  ],
  ['mXSS xmp', 'mxss', '<xmp><p title="</xmp><img src=x onerror=alert(1)>"></xmp>'],
  ['mXSS comment', 'mxss', '<!--><img src=x onerror=alert(1)>-->'],
  ['mXSS cdata', 'mxss', '<svg><![CDATA[><img src=x onerror=alert(1)>]]></svg>'],
  ['mXSS template', 'mxss', '<template><img src=x onerror=alert(1)></template>'],
  [
    'mXSS select',
    'mxss',
    '<select><template><style></select><img src=x onerror=alert(1)></style></template></select>',
  ],
  ['mXSS listing', 'mxss', '<listing>&lt;img src=x onerror=alert(1)&gt;</listing>'],
  ['nested a', 'dom', '<a href="https://a.example"><a href="javascript:alert(1)">x</a></a>'],
  ['target blank no rel', 'tabnab', '<a href="https://evil.example" target="_blank">x</a>'],
  ['unicode scheme', 'url', '<a href="java​script:alert(1)">x</a>'],
  ['unterminated tag', 'dom', '<img src="x" onerror="alert(1)"'],
  ['attr w/o quotes slash', 'handler', '<img/src=x/onerror=alert(1)>'],
  ['text as markup', 'dom', '&lt;script&gt;alert(1)&lt;/script&gt;'],
  ['a mailto', 'url', '<a href="mailto:a@b.co">x</a>'],
  ['a tel', 'url', '<a href="tel:+37499123456">x</a>'],
  ['a relative', 'url', '<a href="/admin">x</a>'],
  [
    'GHSA textarea solidus close',
    'mxss',
    '<textarea><p title="</textarea/><img src=x onerror=alert(1)>">',
  ],
  [
    'GHSA svg SMIL animate',
    'svg',
    '<svg><animate href="#x" attributeName="href" values="javascript:alert(1)" /><a id=x><text>t</text></a></svg>',
  ],
  [
    'GHSA svg SMIL set',
    'svg',
    '<svg><a id=x><text>t</text></a><set href="#x" attributeName="href" to="javascript:alert(1)" /></svg>',
  ],
  ['GHSA xmp raw text', 'mxss', '<xmp><img src=x onerror=alert(1)></xmp>'],
  [
    'GHSA entity-decoded text in script',
    'mxss',
    '<script>&lt;img src=x onerror=alert(1)&gt;</script>',
  ],
  [
    'GHSA entity-decoded text in style',
    'mxss',
    '<style>&lt;/style&gt;&lt;img src=x onerror=alert(1)&gt;</style>',
  ],
  [
    'GHSA entity-decoded text in textarea',
    'mxss',
    '<textarea>&lt;/textarea&gt;&lt;img src=x onerror=alert(1)&gt;</textarea>',
  ],
];
// What the editor is expected to emit (benign) and must survive.
/** What the editor emits (plan §4.1). The structure must survive. */
export const KEEP: readonly string[] = [
  '<h2>Title</h2><h3>Sub</h3><p>Text with <strong>bold</strong>, <em>em</em>, <u>u</u>, <s>s</s>, <code>c</code>.</p>',
  '<ul><li>one</li><li>two</li></ul><ol><li>1</li></ol><blockquote><p>q</p></blockquote>',
  '<pre><code class="language-ts">const a = 1 &lt; 2;</code></pre><hr>',
  '<p><a href="https://example.com/a?b=1&amp;c=2">link</a> and <a href="http://example.org/">another</a></p>',
  '<p>Ադամ — Привет — 日本語 😀 &amp; &lt;tag&gt;</p>',
];
